# Generated by Django 4.1.5 on 2023-01-06 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(blank=True, max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.categoria')),
            ],
        ),
    ]
