# Generated by Django 4.1.5 on 2023-01-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('publicacao', models.CharField(max_length=1000)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usuario')),
            ],
        ),
    ]
