# Generated by Django 4.1.5 on 2023-01-06 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_usuario_post_autor_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
