# Generated by Django 4.1.5 on 2023-01-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_post_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
