# Generated by Django 4.1.5 on 2023-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('AD', 'Administrador'), ('AU', 'Autor'), ('CO', 'Comum')], max_length=30),
        ),
    ]
