# Generated by Django 4.1.4 on 2023-01-12 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_post_categoria_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
